drop table if exists users;
    create table users (
    id integer primary key autoincrement,
    username text not null,
    password text not null,
	m0 int DEFAULT 0,	
	m1 int DEFAULT 0,
	m2 int DEFAULT 0,
	m3 int DEFAULT 0,
	m4 int DEFAULT 0,
	m5 int DEFAULT 0,
	m6 int DEFAULT 0,
	m7 int DEFAULT 0,
	m8 int DEFAULT 0,
	m9 int DEFAULT 0,
	t0 int DEFAULT 1,	
	t1 int DEFAULT 1,
	t2 int DEFAULT 1,
	t3 int DEFAULT 1,
	t4 int DEFAULT 1,
	t5 int DEFAULT 1,
	t6 int DEFAULT 1,
	t7 int DEFAULT 1,
	t8 int DEFAULT 1,
	t9 int DEFAULT 1,
	n0 int DEFAULT 0,	
	n1 int DEFAULT 0,
	n2 int DEFAULT 0,
	n3 int DEFAULT 0,
	n4 int DEFAULT 0,
	n5 int DEFAULT 0,
	n6 int DEFAULT 0,
	n7 int DEFAULT 0,
	n8 int DEFAULT 0,
	n9 int DEFAULT 0,
	email text ,
	phone text
);
