# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_testscore_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testscore',
            name='question',
            field=models.IntegerField(default=1),
        ),
    ]
