# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 13:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_auto_20170307_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='testscore',
            name='itime',
            field=models.DurationField(default=datetime.timedelta(0, 3600)),
        ),
    ]
