# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 11:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0010_auto_20170310_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='apt_test',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 11, 11, 13, 6, 886748)),
        ),
    ]
