# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 11:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0011_apt_test_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apt_test',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
