# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 11:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0017_auto_20170311_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apt_test',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 12, 11, 52, 21, 556279), verbose_name='test end time '),
        ),
    ]
