# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 15:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0024_auto_20170311_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apt_test',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 12, 15, 16, 46, 866530), verbose_name='test end time '),
        ),
    ]
