# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 11:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0029_auto_20170311_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apt_test',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 13, 11, 49, 40, 443342)),
        ),
    ]
