# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 12:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0030_auto_20170312_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apt_test',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 13, 12, 32, 49, 246632)),
        ),
    ]
