# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 13:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0031_auto_20170312_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apt_test',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 14, 13, 53, 5, 281598)),
        ),
    ]
