# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 09:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0032_auto_20170313_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apt_test',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 24, 9, 35, 23, 405291)),
        ),
    ]
