# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 15:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0033_auto_20170323_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apt_test',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 25, 15, 23, 23, 259387)),
        ),
    ]
