# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-01 06:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0034_auto_20170324_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apt_test',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 2, 6, 14, 29, 165767)),
        ),
    ]
