# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default=b'images/q.jpg', upload_to=b'images/'),
        ),
    ]
