# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_standard'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=14),
        ),
    ]
