# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=b'anonymous', max_length=14),
        ),
    ]
