# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20170219_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default=b'bineta', max_length=14),
        ),
    ]
