# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20170221_0422'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.FileField(default=b'profile-pics-17.png', upload_to=b''),
        ),
    ]
