# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oncomp', '0002_auto_20170311_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canswer',
            name='program',
            field=models.TextField(default='Enter Your Program Here'),
        ),
    ]
