# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oncomp', '0004_auto_20170311_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canswer',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('c_cpp', 'C++'), ('javascript', 'Javascript')], default='python', max_length=10),
        ),
    ]
