# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oncomp', '0005_auto_20170311_1516'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='canswer',
            table=None,
        ),
    ]
