# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oncomp', '0006_auto_20170311_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canswer',
            name='program',
            field=models.CharField(default='Enter Your Program Here', max_length=15000),
        ),
    ]
