# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 12:32
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0031_auto_20170312_1232'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oncomp', '0007_auto_20170312_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='compilertestscore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('question', models.IntegerField(default=1)),
                ('itime', models.DurationField(default=datetime.timedelta(0, 3600))),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.Apt_Test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
