# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 13:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oncomp', '0008_compilertestscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compilertestscore',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oncomp.Compilerquestion'),
        ),
    ]
