# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oncomp', '0009_auto_20170313_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compilertestcases',
            name='testcases',
            field=models.TextField(max_length=500),
        ),
    ]
